server:
  port: 8080
  servlet:
    context-path: /profile
spring:
  application:
    name: keycloak-be
  output:
    ansi:
      enabled: always # color log when running in terminal
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/keycloak-be?authSource=admin

idp:
  url: http://localhost:8180
  client-id: german_app
  client-secret: jJ1gdXhJbeOXMnqe1A1jnZVmc3WKCTx3
